### ISSUE TITLE
Allow filtering on BIT fields

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth-multiplayer-data-dashboard#22]
Currently on http://replays.wesnoth.org/dashboard/query when you filter the table for 0 or 1 in the RELOAD field for example nothing matches. I assume that is because in the DB those fields are not the character 0/1 but the ASCII value 0/1 (i.e. NUL/SOH).

**Comment by max-torch** [comment]
I was able to get it working using "="

It seems that for categorical type data, simply typing the category suffices (such as the version field), while for numeric data type fields, you have to use operators.

![image](https://github.com/user-attachments/assets/d0cb4122-156f-4c07-a8cc-9ffb9fb4aed7)

Possible to filter for short and long games in the Game Duration

![image](https://github.com/user-attachments/assets/005ff848-43ce-4219-82fc-0a95c78e45f7)

**Comment by soliton-** [comment]
Ok, I didn't try to find the filter documentation. Would be nice if there was a link to it and if it is a bit dense then would be good to add a direct note with some filter examples.

**Comment by max-torch** [comment]
I do link to the documentation that explains this in the User Guide in the section on Filtering; However, I do agree that it is, in fact, a bit dense to find and understand the information inside the official documentation page, given how it currently looks like and is written.

Thank you so far for this report and discussion and I'll assign this issue to myself.
