### ISSUE TITLE
Request For Replay Link/Title from dashboard-exported CSV data

### ISSUE THREAD

**Issue by MapDesignerOfHiveWorkshop** [wesnoth/wesnoth-multiplayer-data-dashboard#3]
Hello,

May I ask for replay link in the dashboard CSV data sheet exported through the given filters?

**Comment by max-torch** [comment]
The solution for having clickable links inside of Dash DataTable is to embed Markdown inside of the table and use the Markdown syntax for a link.

https://community.plotly.com/t/clickable-link-dash-datatable/54961/3

Possible solution for generating the download URL would be, from the query, to use the Start Date field to extract the year, month, and day; and then the name field for the game name; and then concatenate strings as needed:

```python
f"{base_url}/{year}/{month}/{day}/{game_name}.bz2"
```

**Comment by soliton-** [comment]
This is how the game constructs the URL:
https://github.com/wesnoth/wesnoth/blob/479ccc7fdf6ded23fc332b40ba73930b55855534/src/server/common/dbconn.cpp#L143-L149

**Comment by max-torch** [comment]
We will not focus on this for now because some kind of secure Markdown parsing logic needs to be written to get this to work.
